name: top_grow_project
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  hero_animation: ^1.1.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  http: ^1.3.0
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  youtube_player_iframe: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Qwerty
      fonts:
        - asset: assets/fonts/qwerty.ttf
    - family: Ytrewq
      fonts:
        - asset: assets/fonts/ytrewq.ttf