// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ4hJJEmAJvItxs9-Qsj0cEGGIfdl6Dp0',
    appId: '1:390066654458:web:88fd44fb29fb6892e00d43',
    messagingSenderId: '390066654458',
    projectId: 'topgrowthapp',
    authDomain: 'topgrowthapp.firebaseapp.com',
    storageBucket: 'topgrowthapp.firebasestorage.app',
    measurementId: 'G-7HX4NXY7F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRSVwpOmlAUkMWseDNNqKOgtPZ-s5QxnI',
    appId: '1:390066654458:android:30124d91ed400634e00d43',
    messagingSenderId: '390066654458',
    projectId: 'topgrowthapp',
    storageBucket: 'topgrowthapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJLD-mt1aMyGHqQhi_Z1_6qTxLoFTdxs',
    appId: '1:390066654458:ios:2203456901874aede00d43',
    messagingSenderId: '390066654458',
    projectId: 'topgrowthapp',
    storageBucket: 'topgrowthapp.firebasestorage.app',
    iosBundleId: 'com.example.topGrowProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJJLD-mt1aMyGHqQhi_Z1_6qTxLoFTdxs',
    appId: '1:390066654458:ios:2203456901874aede00d43',
    messagingSenderId: '390066654458',
    projectId: 'topgrowthapp',
    storageBucket: 'topgrowthapp.firebasestorage.app',
    iosBundleId: 'com.example.topGrowProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ4hJJEmAJvItxs9-Qsj0cEGGIfdl6Dp0',
    appId: '1:390066654458:web:c051b9343d80fe89e00d43',
    messagingSenderId: '390066654458',
    projectId: 'topgrowthapp',
    authDomain: 'topgrowthapp.firebaseapp.com',
    storageBucket: 'topgrowthapp.firebasestorage.app',
    measurementId: 'G-ZFCSTEJCBM',
  );
}
